plugins {
    id 'fabric-loom' version '1.7.2'
}

version = '1.0.1-hephaestus'
group = 'com.sakalti'

def minecraftVersion = '1.20.1'
def fabricLoaderVersion = '0.17.2'
def fabricApiVersion = '0.92.6+1.20.1'
def hephaestusProjectId = '667894'
def hephaestusFileId = '7223152'
def hephaestusCoordinate = "curse.maven:hephaestus-fabric-${hephaestusProjectId}:${hephaestusFileId}"

repositories {
    maven { url = 'https://maven.fabricmc.net/' }
    maven { url = 'https://libraries.minecraft.net/' }
    maven { url = 'https://maven.ladysnake.org/releases' }
    maven { url = 'https://www.cursemaven.com' }
    maven { url = 'https://api.modrinth.com/maven' }
    mavenCentral()
    gradlePluginPortal()
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraftVersion}"
    mappings "net.fabricmc:yarn:${minecraftVersion}+build.10:v2"

    modImplementation "net.fabricmc:fabric-loader:${fabricLoaderVersion}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabricApiVersion}"
    modImplementation hephaestusCoordinate

    modImplementation 'dev.onyxstudios.cardinal-components-api:cardinal-components-base:5.2.2'
    modImplementation 'dev.onyxstudios.cardinal-components-api:cardinal-components-entity:5.2.2'
}

processResources {
    inputs.property 'version', project.version
    filesMatching('fabric.mod.json') { expand 'version': project.version }
}

java {
    withSourcesJar()
}

loom {
    splitEnvironmentSourceSets()
}
