package com.sakalti.modifier;
import net.fabricmc.fabric.api.entity.event.v1.ServerEntityCombatEvents; import net.minecraft.text.Text; import net.minecraft.item.ItemStack; import net.minecraft.util.Identifier; import net.minecraft.entity.Entity; import net.minecraft.entity.LivingEntity; import net.minecraft.entity.player.PlayerEntity; import slimeknights.tconstruct.library.modifiers.Modifier; import slimeknights.tconstruct.library.tools.helper.ModifierUtil; import slimeknights.tconstruct.library.tools.context.ToolAttackContext; import slimeknights.tconstruct.library.tools.nbt.IToolStackView; import slimeknights.tconstruct.library.tools.nbt.ModDataNBT; import slimeknights.tconstruct.library.tools.nbt.ToolStack;
public class ItsulicNihilismModifier extends Modifier {
 private static final Identifier KILLS=new Identifier("sakalti", "itsulic_kills"); private static final Identifier BONUS=new Identifier("sakalti", "itsulic_bonus"); private static final float DIVISOR=25000f;
 public static void initEvents(){ServerEntityCombatEvents.AFTER_KILLED_OTHER_ENTITY.register(ItsulicNihilismModifier::afterKilled);}
 private static void afterKilled(net.minecraft.server.world.ServerWorld world,Entity killer,LivingEntity killed){if(!(killer instanceof PlayerEntity p))return;ItemStack stack=p.getMainHandStack();ToolStack tool;try{tool=ToolStack.from(stack);}catch(Exception ex){return;}int level=ModifierUtil.getModifierLevel(stack,new slimeknights.tconstruct.library.modifiers.ModifierId("sakalti","itsulic_nihilism"));if(level<=0)return;ModDataNBT data=tool.getPersistentData();int kills=data.get(KILLS,(tag,key)->tag.getInt(key));float bonus=data.get(BONUS,(tag,key)->tag.getFloat(key));kills++;float gain=Math.round(world.random.nextFloat()*killed.getMaxHealth()*100f)/100f/DIVISOR;bonus=Math.round((bonus+gain)*100f)/100f;data.putInt(KILLS,kills);data.putFloat(BONUS,bonus);}
 @Override public float getEntityDamage(IToolStackView tool,int level,ToolAttackContext ctx,float baseDamage,float damage){Float b=tool.getPersistentData().get(BONUS,(tag,key)->tag.getFloat(key));return damage+(b==null?0:b);}
 @Override public Text getDisplayName(IToolStackView tool,int level){Integer k=tool.getPersistentData().get(KILLS,(tag,key)->tag.getInt(key));Float b=tool.getPersistentData().get(BONUS,(tag,key)->tag.getFloat(key));if(k!=null&&k>0)return Text.literal(super.getDisplayName(level).getString()+" [Killed: "+k+"] [Bonus: "+(b==null?0f:b)+"]");return super.getDisplayName(level);}
}
